# Googleドライブから学習データをロード

In [1]:
from google.colab import drive
drive.mount('./gdrive')

Mounted at ./gdrive


In [2]:
!cp '/content/gdrive/MyDrive/ReversiTrainData/X_dataset.npy' ./
!cp '/content/gdrive/MyDrive/ReversiTrainData/y_dataset.npy' ./

In [3]:
import numpy as np
X_dataset = np.load('X_dataset.npy')
y_dataset = np.load('y_dataset.npy')
print(len(X_dataset))

2005741


# 盤面を180度回転

In [25]:
X_temp_dataset = X_dataset.reshape([len(X_dataset), 8, 8])
y_temp_dataset = y_dataset.reshape([len(y_dataset), 8, 8])
X_temp_dataset = np.rot90(X_temp_dataset, 2, axes=(1, 2))
y_temp_dataset = np.rot90(y_temp_dataset, 2, axes=(1, 2))
X_temp_dataset = X_temp_dataset.reshape([len(X_dataset), 64])
y_temp_dataset = y_temp_dataset.reshape([len(y_dataset), 64])

In [27]:
print(X_dataset[0])
print(X_dataset[0].reshape([8, 8]))
print(X_temp_dataset[0])
print(X_temp_dataset[0].reshape([8, 8]))

print(y_dataset[0])
print(y_dataset[0].reshape([8, 8]))
print(y_temp_dataset[0])
print(y_temp_dataset[0].reshape([8, 8]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 1 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 2 1 0 0 0]
 [0 0 0 1 2 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 1 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 2 1 0 0 0]
 [0 0 0 1 2 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0 0 0 0

In [29]:
X_dataset = np.vstack([X_dataset, X_temp_dataset])
y_dataset = np.vstack([y_dataset, y_temp_dataset])

In [30]:
print(len(X_dataset))

4011482


# 保存

In [32]:
# npyで保存
np.save('X_dataset2', X_dataset)
np.save('y_dataset2', y_dataset)

In [33]:
!cp 'X_dataset2.npy' '/content/gdrive/MyDrive/ReversiTrainData'
!cp 'y_dataset2.npy' '/content/gdrive/MyDrive/ReversiTrainData'